bug(detail): submit comment
cse110-fa21-group29/cse110-fa21-group29 pull request #117
Opened 2021-11-20 18:45 UTC by FangchengDou

add submit img feature but I don't know how to use onchange=""call the function,  error isthis.uploadImg is not a function. This bug also exists on contribute page. There are lots of style bugs or syntax errors on this page. The best way is to rewrite it. What do you think? If the bad syntax (eg. all elements are class) doesn't obstruct next step development, I will just correct the style, if it obstruct, I will rewrite.
close #116

2021-11-20 19:27 UTC, jbutera94 requested changes
Looks good to me, left one suggestion. For the syntax errors, I think it's good enough for now. I wouldn't spend too much time perfecting it, and instead would continue iterating the design with Viki. Also don't worry about the errors in Codacy, it's not completely set up yet.

2021-11-20 19:27 UTC, jbutera94 commented on source/components/recipe-details/recipe-details.html
> +      <input type="file" id="submit-img" onchange="this.uploadImg(event)" />
I don't see the file input. Are users supposed to be able to upload images in comments?

Also I think for the `uploadImg` function, using `onchange="uploadImg(event)"` should work. Let me know if it doesn't.

2021-11-20 19:32 UTC, FangchengDou commented on source/components/recipe-details/recipe-details.html
> +      <input type="file" id="submit-img" onchange="this.uploadImg(event)" />
Viki says there should be a upload img feature when comment. But if you think it not good, I can remove it. When you click on the image, you should be able to submit the img. Same with contribute page. But this function is doesn't work also on contribute page.

2021-11-21 22:23 UTC, jbutera94 commented on source/components/recipe-details/recipe-details.html
> +      <input type="file" id="submit-img" onchange="this.uploadImg(event)" />
Hmm... I'm not sure why that wouldn't work (also sorry, I just saw this comment).

2021-11-21 22:44 UTC, jbutera94 commented on source/components/recipe-details/recipe-details.html
> +      <input type="file" id="submit-img" onchange="this.uploadImg(event)" />
@FangchengDou Let's focus on the other pages for now. We can figure out why this isn't working once we have the CRUD pages improved.

2021-11-24 01:13 UTC, closed without merging