Feat/172 pagination functionality
cse110-fa21-group29/cse110-fa21-group29 pull request #289
Opened 2021-12-05 10:33 UTC by tvdao

Implemented pagination

It updates the URL to the page number that was clicked

Close #172

2021-12-05 21:21 UTC, jbutera94 requested changes
Looks good overall, left some suggestions. Also for some reason it looks like you deleted an ADR (`specs/adrs/111921-recipe-json-structure.md`)? If this was unintentional, please try to re-add it back.

2021-12-05 21:21 UTC, jbutera94 commented on source/components/recipe-search/recipe-search.js
> +      leftArrow.addEventListener("click", () => {
For now, let's try extracting this callback into its own function, then calling it in the event listener. See above (ex: line 27) for examples of this. Then you can replace all instances of `thisContainer` with `this`. It should look something like below when complete:
```javascript
leftArrow.addEventListener("click", () => {
  this.previousPage();
}
```

2021-12-05 21:21 UTC, jbutera94 commented on source/components/recipe-search/recipe-search.js
> +        let equalIndex = pageChunk.indexOf("=");
Please use `const` (except for `currPageNum` which is modified below).

2021-12-05 21:21 UTC, jbutera94 commented on source/components/recipe-search/recipe-search.js
> +    else {
Please rearrange as below:
```suggestion
    } else {
    // For the case that pagination is not required
```

2021-12-05 21:21 UTC, jbutera94 commented on source/components/recipe-search/recipe-search.js
> +      rightArrow.addEventListener("click", () => {
Please extract callback into its own function and change all `thisContainer` to `this`, see above for example for `leftArrow`.

2021-12-05 21:21 UTC, jbutera94 commented on source/components/recipe-search/recipe-search.js
> +        anchorTag.addEventListener("click", () => {
Please extract callback into its own function and change all `thisContainer` to `this`, see above for example for `leftArrow`.

2021-12-05 21:21 UTC, jbutera94 commented on source/components/recipe-search/recipe-search.js
> +          let pageRecipes = searchRecipe.slice(recipeStart, recipeEnd);
Instead of referencing `searchRecipe` inside the callback, please have a `searchRecipe` parameter for the function that this callback will become. Also please use `const`.

2021-12-05 21:21 UTC, jbutera94 commented on source/components/recipe-search/recipe-search.js
> +          let currPage = anchorTag.innerHTML;
Instead of referencing `anchorTag` inside the callback, please have an `currPage` parameter for the function that this callback will become.

2021-12-05 21:21 UTC, jbutera94 commented on source/components/recipe-search/recipe-search.js
> +          let equalIndex = pageChunk.indexOf("=");
Please use `const`.

2021-12-05 21:21 UTC, jbutera94 commented on source/components/recipe-search/recipe-search.js
> +      let leftArrow = document.createElement("a");
Please use `const` for both variables. Also I believe there is a typo, should `pagDiv` be `pageDiv`?

2021-12-05 21:21 UTC, jbutera94 commented on source/components/recipe-search/recipe-search.js
> +         */
Not sure what this comment is referencing? Also we don't need a JSDocs-style comment on a non-function.

2021-12-05 21:21 UTC, jbutera94 commented on source/components/recipe-search/recipe-search.js
> +  }
Please delete this function if you are not using it.

2021-12-05 21:21 UTC, jbutera94 commented on source/components/recipe-search/recipe-search.js
> +        currPageNum = parseInt(currPageNum);
Please specify base 10 for the `parseInt`. See below:
```suggestion
        currPageNum = parseInt(currPageNum, 10);
```

2021-12-05 22:08 UTC, tvdao commented on source/components/recipe-search/recipe-search.js
> +      let leftArrow = document.createElement("a");
pagDiv for pagination div in the html

2021-12-06 02:48 UTC, jbutera94 approved these changes
Looks good to me. Not sure how to fix the codacy issues easily though...

2021-12-06 04:33 UTC, merged