Feat/306 improve nav bar recipe card
cse110-fa21-group29/cse110-fa21-group29 pull request #327
Opened 2021-12-07 06:48 UTC by keskinmbaha

Finished all the suggested styling comments we had from the meeting.

#Closes 306

2021-12-07 07:42 UTC, jbutera94 requested changes
Looks good, left one small suggestion.

2021-12-07 07:42 UTC, jbutera94 commented on source/components/common/nav-bar/common-nav-bar.css
> +.div-links {
I'm wondering if `.nav-link-container` makes more sense as the name.

2021-12-07 08:44 UTC, keskinmbaha commented
Have to fix the search page routing system.

2021-12-07 23:11 UTC, jbutera94 requested changes

2021-12-07 23:11 UTC, jbutera94 commented on source/components/common/nav-bar/common-nav-bar.html
> +      href="#/recipes/search?query=&glutenFree=true&healthy=true&highProtein=true&vegan=true&vegetarian=true?page=1"
Changing the search URL to `#/recipes/search?query=&glutenFree=true&healthy=true&highProtein=true&vegan=true&vegetarian=true&page=1` should fix the routing issue.

2021-12-08 02:38 UTC, jbutera94 approved these changes
Looks good!

2021-12-08 02:38 UTC, merged