Feat/18 recipe details
cse110-fa21-group29/cse110-fa21-group29 pull request #46
Opened 2021-11-15 23:01 UTC by z1tang

2021-11-16 03:33 UTC, vikizzz commented
For CSS, please change all absolute units to relative units. In addition, missing picture upload section and submit button in the comment section.

2021-11-16 03:50 UTC, jbutera94 requested changes
Hey Zhuoran,

Thanks for working on the recipe details page. Like Viki mentioned, please replace all absolute positioning, like `position: absolute`, `width`, `height`, `top`, and `left` with more relative units. For instance, instead of `width: 200px`, you could replace it with something like `width: 50%`. Additionally, instead of `top` and `left` for the absolute positioning, please use margin and padding to position elements around each other. Feel free to use flexbox and grid as well since those are relative.

Also when you are done, please ensure you have prettier and eslint running on your machine. As long as you run `npm install` and `npx husky install`, you should be good to go. This will make sure that the PR passes the linter checks shown at the bottom of this page.

2021-11-16 03:50 UTC, jbutera94 commented on source/components/recipe-details/detailpage.html
> +          </h3>
Please separate into three `<div>`s (author name, uploaded date, url) instead of the `<h3>`. I don't think `<br>`s need to be inside the `<h3>`.

2021-11-16 03:50 UTC, jbutera94 commented on source/components/recipe-details/detailpage.html
> +          <div class="ing-title">
Please don't abbreviate class names. See below:
```suggestion
          <div class="ingredients-title">
```

2021-11-16 03:50 UTC, jbutera94 commented on source/components/recipe-details/detailpage.html
> +          <div class="ing-list">
Same as above:
```suggestion
          <div class="ingredients-list">
```

2021-11-16 03:50 UTC, jbutera94 commented on source/components/recipe-details/detailpage.html
> +        </div>
For generic styling that will apply to all comment boxes, please use a class. Here, I don't think we need IDs for these elements, since we're not individually identifying them in JS or CSS. Also, I think the only difference between the reply comments and the parent comment is that the replies have some margin on the left to indent them, so we can give them a class like `comment-box-reply` that has the reply-specific styling. See below:
```suggestion
        <!-- Direction box-->
        <div class="comment-box">
          <div class="comment-box comment-box-reply">
            <div class="comment box comment-box-reply"></div>
          </div>
          <div class="comment-box">
            <div class="comment-box comment-box-reply"></div>
            <div class="comment-box comment-box-reply"></div>
          </div>
        </div>
```

2021-11-16 03:50 UTC, jbutera94 commented on source/components/recipe-details/detailpage.html
> +    </footer>
Please remove, this will be in a separate component.

2021-11-16 03:50 UTC, jbutera94 commented on source/components/recipe-details/style.css
> +        }
It seems each of these IDs has the exact same styling except for the margin values. Please replace with a generic class like `comment-box` that has all of the styling for every comment box, and `comment-box-reply` that has the margin left that only replies have.

2021-11-16 04:08 UTC, jbutera94 commented on source/components/recipe-details/detailpage.html
> +        />
Right now, the recipe image is stretch on the page. Please add `object-fit: cover` for now.

2021-11-17 10:53 UTC, jbutera94 requested changes
Looks good overall, just left a couple quick suggestions.

2021-11-17 10:53 UTC, jbutera94 commented on source/components/recipe-details/detailpage.html
> +          </div>
Maybe replace `comment-box-reply` with `comment-box-reply-container` and the `-reply1` and `-reply2` with just `-reply`? See below:
```suggestion
          <div class="comment-box-reply-container">
            <div class="comment-box-reply">display user input here</div>
            <div class="comment-box-reply">display user input here</div>
          </div>
```

2021-11-17 10:53 UTC, jbutera94 commented on source/components/recipe-details/style.css
> +}
Please rename to `.comment-box-reply-container`.

2021-11-17 10:53 UTC, jbutera94 commented on source/components/recipe-details/style.css
> +}
Please consolidate into one class `.comment-box-reply`. The `margin-bottom` that only appears inside `.comment-box-reply2` can be replaced by adding `padding-bottom` to the container class. See below:
```suggestion
.comment-box-reply {
  height: 10vh;
  margin-top: 1%;
  margin-left: 1%;
  margin-right: 1%;
  border: 1px solid #000000;
  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
  padding: 1%;
}
```

2021-11-17 21:44 UTC, jbutera94 approved these changes

2021-11-17 21:57 UTC, merged